### ISSUE TITLE
Implement HHG, Pearson/RV/Cca, Spearman/Kendall (Sambit)

### ISSUE THREAD

**Issue by junhaobearxiong** [neurodata/mgcpy-old#12]
- [ ] DoD: Contribute to corresponding plots in Figure 2 & Table 1 of https://arxiv.org/pdf/1609.05148.pdf

**Comment by jovo** [comment]
be specific

**Comment by jovo** [comment]
@sampan501 we do not need MIC.  and we might not need dHSIC or correlation.
does scipy have pearson? rv? cca?  spearman? kendall?
dHISC is equivalent to Dcorr: https://arxiv.org/abs/1806.05514, so we just need a transformation there, and maybe a kernel.

**Comment by sampan501** [comment]
Ok, I will keep these in mind and look into scipy's implementation for these. I will mention this in our presentation today but looking through scipy.stats.pearsonr it seems to only work for 1-dimensional arrays. However, I may be able to integrate it within the current code to optimize it for our implementation. I know for a fact the spearman is in scipy.stats but will look up the other ones.
